export const AMBIGUOUS_CHARACTERS = '0Oo!iIlL17|¦';
export const LOWERCASE = 'abcdefghijklmnopqrstuvwxyz'.split('');
export const UPPERCASE = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');
export const DIGITS = '0123456789'.split('');
export const SYMBOLS = '!#$%&()*+,-./:;<?@[]^_{|}~'.split(''); // no "'\`'
export const PASSWORD_DEFAULT_LENGTH_MIN = 12;
export const PASSWORD_DEFAULT_LENGTH_MAX = 24;
export const PASSWORD_MIN_LENGTH = 8;
export const PASSWORD_MAX_LENGTH = 128;
export const PIN_DEFAULT_LENGTH = 4;
export const PIN_MIN_LENGTH = 3;
export const PIN_MAX_LENGTH = 12;
export const PASSPHRASE_DEFAULT_SIZE = 4;
export const PASSPHRASE_MIN_SIZE = 3;
export const PASSPHRASE_MAX_SIZE = 15;
